# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParkingSpot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, latitude: float=None, longitude: float=None, status: str=None):  # noqa: E501
        """ParkingSpot - a model defined in Swagger

        :param id: The id of this ParkingSpot.  # noqa: E501
        :type id: int
        :param name: The name of this ParkingSpot.  # noqa: E501
        :type name: str
        :param latitude: The latitude of this ParkingSpot.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this ParkingSpot.  # noqa: E501
        :type longitude: float
        :param status: The status of this ParkingSpot.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'latitude': float,
            'longitude': float,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'latitude': 'latitude',
            'longitude': 'longitude',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._latitude = latitude
        self._longitude = longitude
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'ParkingSpot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParkingSpot of this ParkingSpot.  # noqa: E501
        :rtype: ParkingSpot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ParkingSpot.

        identity id of the parking spot  # noqa: E501

        :return: The id of this ParkingSpot.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ParkingSpot.

        identity id of the parking spot  # noqa: E501

        :param id: The id of this ParkingSpot.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ParkingSpot.

        meaningful name of the parking spot, easy for human being  # noqa: E501

        :return: The name of this ParkingSpot.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ParkingSpot.

        meaningful name of the parking spot, easy for human being  # noqa: E501

        :param name: The name of this ParkingSpot.
        :type name: str
        """

        self._name = name

    @property
    def latitude(self) -> float:
        """Gets the latitude of this ParkingSpot.

        Latitude coordinate of this parking spot  # noqa: E501

        :return: The latitude of this ParkingSpot.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this ParkingSpot.

        Latitude coordinate of this parking spot  # noqa: E501

        :param latitude: The latitude of this ParkingSpot.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this ParkingSpot.

        longitude coordinate of this parking spot  # noqa: E501

        :return: The longitude of this ParkingSpot.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this ParkingSpot.

        longitude coordinate of this parking spot  # noqa: E501

        :param longitude: The longitude of this ParkingSpot.
        :type longitude: float
        """

        self._longitude = longitude

    @property
    def status(self) -> str:
        """Gets the status of this ParkingSpot.

        available status for resveration  # noqa: E501

        :return: The status of this ParkingSpot.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ParkingSpot.

        available status for resveration  # noqa: E501

        :param status: The status of this ParkingSpot.
        :type status: str
        """
        allowed_values = ["available", "booked"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
